version: "3"

services:
  postgres:
    image: postgres:14
    command: postgres -c 'max_connections=500'
    restart: always
    container_name: pkt-strapi-postgres
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: local
      POSTGRES_PASSWORD: local
      POSTGRES_DB: database
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 10s
      timeout: 30s
      retries: 5
      start_period: 60s

volumes:
  postgres-data:
    driver: local
